### ISSUE TITLE
你个后台是用什么搭建的

### ISSUE THREAD

**Issue by Joel-Mracek** [a695979515/enterprise#10]
我想把这个项目改成BOOT 的

**Comment by ChenLin12138** [comment]
我也想改。弄成spring boot + thymeleaf

**Comment by ChenLin12138** [comment]
也可以正成spring boot打成可执行war，这样就用在服务器上安装tomcat了。

**Comment by dongjiashun** [comment]
"/front/service/serviceList";没有这个接口，没法显示服务领域的东西

**Comment by gaoyuan888** [comment]
收到
