### ISSUE TITLE
http500求解

### ISSUE THREAD

**Issue by Atoers** [a695979515/enterprise#27]
org.apache.jasper.JasperException: 在 [23] 行处理 [/front/common/common.jsp] 时发生异常

20: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
21: <html>
22: <head>
23:     <meta name="description" content="<%=SystemManage.getInstance().getSystemSetting().getDescription() %>"/>
24:     <meta name="keywords" content="<%=SystemManage.getInstance().getSystemSetting().getKeywords() %>"/>
25:     <meta http-equiv="X-UA-Compatible" content="IE=edge">
26:     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

java.lang.NullPointerException: Cannot invoke "com.enterprise.entity.SystemSetting.getDescription()" because the return value of "com.enterprise.core.SystemManage.getSystemSetting()" is null

**Comment by iampangpang123** [comment]
我也是这样
