### ISSUE TITLE
运行之后500

### ISSUE THREAD

**Issue by Syrannosauruse** [a695979515/enterprise#8]
富豪锅 a695979515    请教 500错误
HTTP Status 500 – Internal Server Error
An exception occurred processing JSP page [/front/common/common.jsp] at line [23]
Exception

org.apache.jasper.JasperException: An exception occurred processing JSP page [/front/common/common.jsp] at line [23]

20: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
21: <html>
22: <head>
23:     <meta name="description" content="<%=SystemManage.getInstance().getSystemSetting().getDescription() %>"/>
24:     <meta name="keywords" content="<%=SystemManage.getInstance().getSystemSetting().getKeywords() %>"/>
25:     <meta http-equiv="X-UA-Compatible" content="IE=edge">
26:     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

**Comment by Syrannosauruse** [comment]
href="<%=SystemManage.getInstance().getSystemSetting().getImageRootPath()%><%=SystemManage.getInstance().getSystemSetting().getFavicon()%>"> 请教

**Comment by iampangpang123** [comment]
我的也是这样，请问你是怎么解决的

**Comment by junges521** [comment]
如何解决它的呢

**Comment by gaoyuan888** [comment]
收到
